version: '3'
services:
  postgres_db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=thenewshit
      - POSTGRES_DB=weather_db
  mysql_db:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=thenewshit
      - MYSQL_PASSWORD=thenewshit
      - MYSQL_USER=root
      - MYSQL_DATABASE=temperature_db
  load-aggregate-app:
    restart: "no"
    build: 
      context: ./load-aggregate-app
      dockerfile: Dockerfile
    volumes:
      - ./server:/app:rw
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - MONGO_URI=mongodb://mongodb:27017/hsse-project
    depends_on:
      - postgres_db
      - mysql_db
  reporting-app:
    build:
      context: ./reporting-app
      dockerfile: Dockerfile
    volumes:
      - ./reactjs:/app:rw
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - BACKEND_SERVER=http://localhost:3050/api
    depends_on:
      mysql_db
volumes:
  postgres_data:
  mysql_data: